services:
  seq:
    image: datalust/seq:2025.2
    container_name: seq
    ports:
      - "5341:80"
    volumes:
      - seq-data:/data
      - seq-logs:/logs
    environment:
      - ACCEPT_EULA=Y
      - SEQ_STORAGE_PATH=/data
      - SEQ_PASSWORD=12345

volumes:
  seq-data:
  seq-logs:
